"""empty message

Revision ID: 206ffd983c5c
Revises: b325f36f9557
Create Date: 2021-08-11 00:20:03.794167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206ffd983c5c'
down_revision = 'b325f36f9557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('cha_time', sa.Integer(), nullable=True))
    op.add_column('challenge', sa.Column('sent_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('best_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'best_time')
    op.drop_column('challenge', 'sent_time')
    op.drop_column('challenge', 'cha_time')
    # ### end Alembic commands ###
