"""empty message

Revision ID: 8f67279cecfc
Revises: 206ffd983c5c
Create Date: 2021-08-16 23:19:54.224393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f67279cecfc'
down_revision = '206ffd983c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('theme', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'theme')
    # ### end Alembic commands ###
